import React, { useState } from 'react';
import { Resource } from '../types';
import { 
  Printer, 
  Download, 
  Copy, 
  CheckCircle2, 
  X, 
  Phone, 
  MapPin, 
  Bed, 
  Dog, 
  ShieldCheck, 
  Sparkles,
  Heart,
  Scale
} from 'lucide-react';
import confetti from 'canvas-confetti';

interface PocketResourceDirectoryModalProps {
  isOpen: boolean;
  onClose: () => void;
  resources: Resource[];
}

export const PocketResourceDirectoryModal: React.FC<PocketResourceDirectoryModalProps> = ({
  isOpen,
  onClose,
  resources,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const topShelters = resources.filter((r) => r.category === 'shelter' || r.category === 'warming_cooling').slice(0, 6);
  const topFood = resources.filter((r) => r.category === 'food').slice(0, 4);
  const topMedical = resources.filter((r) => r.category === 'medical' || r.category === 'vet').slice(0, 4);

  const generatePlainTextDirectory = () => {
    return `=====================================================
DAISY'S HELPING PAWS - POCKET SURVIVAL & SHELTER DIRECTORY
Emergency Aid & Community Resources (Printable Offline Edition)
=====================================================

24/7 EMERGENCY CRISIS HOTLINES (FREE & CONFIDENTIAL):
- 988 Suicide & Mental Health Crisis Lifeline: Dial 988 (Call or Text)
- 211 Community Help, Shelter & Utility Line: Dial 211 or (877) 211-9274
- Veterans Crisis Line: Dial 988, then press 1, or Text 838255
- National Domestic Violence Safe Line: 1-800-799-SAFE (7233)
- Poison Control Center: 1-800-222-1222

-----------------------------------------------------
EMERGENCY OVERNIGHT SHELTERS & WARMING CENTERS
-----------------------------------------------------
${topShelters.map((s, i) => `${i + 1}. ${s.name}
   Address: ${s.address}, ${s.city}
   Phone: ${s.phone || 'Walk-in'}
   Hours: ${s.hours}
   Pets Allowed: ${s.petFriendly ? 'YES (Pet Friendly)' : 'Service Animals Only'}
   Open Beds: ${s.bedsAvailable ? `${s.bedsAvailable} of ${s.totalBeds || 65} open` : 'Call for intake'}
   Intake: ${s.intakeRequirements || 'Walk-in welcome'}`).join('\n\n')}

-----------------------------------------------------
FREE HOT MEALS & FOOD PANTRIES
-----------------------------------------------------
${topFood.map((f, i) => `${i + 1}. ${f.name}
   Address: ${f.address}, ${f.city}
   Phone: ${f.phone || 'Walk-in'}
   Hours: ${f.hours}
   Pets: ${f.petFriendly ? 'Pet food available' : 'Standard'}
   Notes: ${f.description}`).join('\n\n')}

-----------------------------------------------------
FREE STREET MEDICINE & PET CARE CLINICS
-----------------------------------------------------
${topMedical.map((m, i) => `${i + 1}. ${m.name} (${m.category === 'vet' ? 'Veterinary' : 'Medical'})
   Address: ${m.address}, ${m.city}
   Phone: ${m.phone || 'Walk-in'}
   Hours: ${m.hours}
   Services: ${m.servicesOffered.join(', ')}`).join('\n\n')}

-----------------------------------------------------
YOUR LEGAL RIGHTS ON THE STREET (Daisy's Quick Card):
- 4th Amendment: Police or city workers cannot seize or destroy your personal property without adequate written notice and safe storage.
- Service / ESA Animals: Under ADA & Fair Housing, emergency shelters must accommodate genuine service animals and reasonably accommodate emotional support companions.
- Right to Shelter: If no accessible shelter bed is available, camping in public spaces is protected under federal civil rights precedents.

-----------------------------------------------------
Generated by Daisy's Helping Paws • Web & Android Aid Network
=====================================================`;
  };

  const handleCopyText = () => {
    navigator.clipboard.writeText(generatePlainTextDirectory());
    setCopied(true);
    confetti({ particleCount: 40, spread: 50 });
    setTimeout(() => setCopied(false), 2500);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-slate-950/75 backdrop-blur-xs animate-fade-in">
      <div className="bg-white rounded-2xl max-w-3xl w-full max-h-[90vh] flex flex-col shadow-2xl border border-slate-200 overflow-hidden">
        
        {/* Header */}
        <div className="p-4 bg-indigo-950 text-white flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-10 h-10 rounded-xl bg-amber-400 text-slate-950 flex items-center justify-center font-bold text-lg shrink-0">
              📄
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-base font-bold font-heading">
                  Daisy's Pocket Survival & Shelter Directory
                </h2>
                <span className="px-2 py-0.5 rounded-full bg-emerald-500/30 text-emerald-300 text-[10px] font-bold">
                  Print & Offline Ready
                </span>
              </div>
              <p className="text-xs text-indigo-200 mt-0.5">
                Foldable pocket card with emergency phone numbers, hot meals, open beds, and civil rights.
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-white rounded-lg transition"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Action Toolbar */}
        <div className="px-4 py-2.5 bg-slate-100 border-b border-slate-200 flex items-center justify-between gap-2 flex-wrap">
          <span className="text-xs text-slate-600 font-medium">
            Formatted for 8.5x11" or pocket folding
          </span>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyText}
              className="px-3 py-1.5 bg-white hover:bg-slate-50 text-slate-700 border border-slate-200 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition shadow-2xs"
            >
              {copied ? <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-500" />}
              <span>{copied ? 'Copied to Clipboard!' : 'Copy Text'}</span>
            </button>

            <button
              onClick={handlePrint}
              className="px-3.5 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-xs font-bold flex items-center gap-1.5 transition shadow-xs"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Pocket Guide</span>
            </button>
          </div>
        </div>

        {/* Scrollable Printable Booklet Content */}
        <div className="p-4 sm:p-6 overflow-y-auto flex-1 space-y-5 text-slate-800 font-sans print:p-0 print:text-black">
          
          {/* Top Banner (Print View) */}
          <div className="border-b-2 border-indigo-900 pb-3 flex items-center justify-between">
            <div>
              <h1 className="text-lg font-black text-indigo-950 uppercase tracking-tight">
                🐾 Daisy's Helping Paws — Emergency Pocket Guide
              </h1>
              <p className="text-xs text-slate-600 font-medium">
                24/7 Community Resources, Open Beds, Hot Meals & Street Defense
              </p>
            </div>
            <div className="text-right text-[10px] text-slate-500">
              <span>Always Free • No ID Required</span>
            </div>
          </div>

          {/* Crisis Hotlines Grid */}
          <div className="p-3.5 rounded-xl bg-rose-50 border border-rose-200 grid grid-cols-1 sm:grid-cols-3 gap-2 text-xs">
            <div className="p-2 bg-white rounded-lg border border-rose-100 shadow-2xs">
              <span className="text-[10px] font-bold uppercase text-rose-600 block">Crisis & Mental Health</span>
              <strong className="text-sm text-slate-900 font-heading block">Dial 988</strong>
              <span className="text-[10px] text-slate-500">Call or Text 24/7 (Free)</span>
            </div>

            <div className="p-2 bg-white rounded-lg border border-rose-100 shadow-2xs">
              <span className="text-[10px] font-bold uppercase text-blue-600 block">Shelter & Food Helpline</span>
              <strong className="text-sm text-slate-900 font-heading block">Dial 211</strong>
              <span className="text-[10px] text-slate-500">Community intake dispatch</span>
            </div>

            <div className="p-2 bg-white rounded-lg border border-rose-100 shadow-2xs">
              <span className="text-[10px] font-bold uppercase text-purple-600 block">Domestic Violence Line</span>
              <strong className="text-sm text-slate-900 font-heading block">1-800-799-7233</strong>
              <span className="text-[10px] text-slate-500">Confidential safe shelter</span>
            </div>
          </div>

          {/* Shelters Section */}
          <div className="space-y-2">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 flex items-center gap-1.5 border-b pb-1">
              <Bed className="w-4 h-4 text-indigo-600" />
              <span>Emergency Shelters & Overnight Beds</span>
            </h3>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5">
              {topShelters.map((s) => (
                <div key={s.id} className="p-2.5 rounded-xl bg-slate-50 border border-slate-200 text-xs space-y-1">
                  <div className="flex items-start justify-between gap-1">
                    <strong className="font-bold text-slate-900 text-xs">{s.name}</strong>
                    {s.bedsAvailable && (
                      <span className="px-1.5 py-0.2 rounded bg-indigo-600 text-white text-[10px] font-bold shrink-0">
                        {s.bedsAvailable} beds open
                      </span>
                    )}
                  </div>
                  <div className="text-[11px] text-slate-600 flex items-center gap-1">
                    <MapPin className="w-3 h-3 text-slate-400 shrink-0" />
                    <span>{s.address}, {s.city}</span>
                  </div>
                  <div className="text-[11px] text-slate-600 flex items-center justify-between">
                    <span>📞 {s.phone || 'Walk-in'}</span>
                    <span className="font-semibold text-indigo-700">{s.petFriendly ? '🐾 Pets OK' : 'Service Animals'}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Free Meals & Clinics Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            
            {/* Hot Meals */}
            <div className="space-y-2">
              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 flex items-center gap-1.5 border-b pb-1">
                <span>🍱 Free Meals & Pantries</span>
              </h3>
              <div className="space-y-2">
                {topFood.map((f) => (
                  <div key={f.id} className="p-2 bg-amber-50/60 rounded-lg border border-amber-200 text-xs">
                    <strong className="text-slate-900 text-xs block">{f.name}</strong>
                    <p className="text-[11px] text-slate-600">{f.address} • {f.hours}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Medical & Pet Clinics */}
            <div className="space-y-2">
              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 flex items-center gap-1.5 border-b pb-1">
                <span>🩺 Free Medical & Street Vet</span>
              </h3>
              <div className="space-y-2">
                {topMedical.map((m) => (
                  <div key={m.id} className="p-2 bg-teal-50/60 rounded-lg border border-teal-200 text-xs">
                    <strong className="text-slate-900 text-xs block">{m.name}</strong>
                    <p className="text-[11px] text-slate-600">{m.address} • {m.hours}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Civil Rights Street Defense Box */}
          <div className="p-3.5 rounded-xl bg-slate-900 text-white text-xs space-y-1.5">
            <div className="flex items-center gap-2 text-amber-400 font-bold">
              <Scale className="w-4 h-4" />
              <span>Know Your Civil Rights on the Street</span>
            </div>
            <ul className="text-[11px] text-slate-300 space-y-1 list-disc pl-4 leading-relaxed">
              <li><strong>4th Amendment Property:</strong> You cannot have your tent, identification, medication, or belongings confiscated or destroyed without 72-hour notice and secure city storage.</li>
              <li><strong>Service Animals:</strong> Emergency shelters and public transit cannot turn away ADA service dogs or charge extra pet deposits.</li>
              <li><strong>Right to Shelter:</strong> You have the right to request reasonable disability accommodations and family unit placement.</li>
            </ul>
          </div>
        </div>

        {/* Footer */}
        <div className="p-3 bg-slate-100 border-t border-slate-200 flex items-center justify-between text-xs text-slate-500">
          <span>Need help filing benefits or legal appeals? Use the AI Caseworker tab.</span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 bg-slate-800 text-white rounded-lg font-semibold hover:bg-slate-700 transition"
          >
            Close Guide
          </button>
        </div>
      </div>
    </div>
  );
};
